# Generated by Django 3.0.6 on 2020-06-12 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('goods', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=20)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
    ]
